### ISSUE TITLE
Generazione riassunto

### ISSUE THREAD

**Issue by Tambup** [Tambup/FSM_algorithm#15]
**Slide 106**

Per ogni automa considerato, sia esso fornito in ingresso o prodotto in uscita (componente della rete, spazio, diagnosticatore, ...), generare un riassuntoche ne compendi le dimensioni (numero di stati e numero di transizioni).

**Comment by stoppini** [comment]
aggiunti i riassunti per i punti 1,2,4 ( gli altri abbiamo regex quindi non penso abbia senso ) per l'output
input prima bisogna vedere che metterci

**Comment by Tambup** [comment]
Fare input
